spring:
  application:
    name: blog-service
  cloud:
    stream:
      kafka:
        binder:
          brokers: localhost:9092
          auto-add-partitions: true
          headers:
            - X-B3-TraceId
            - X-B3-SpanId
            - X-B3-Sampled
            - X-B3-ParentSpanId
            - X-Span-Name
            - X-Span-Export
      bindings:
        output:
          destination: blog-service.view-count
          # content-type: application/json
          producer:
            partition-count: 3
        input:
          destination: blog-service.view-count
          # content-type: application/json
          consumer:
            concurrency: 3

server:
  port: 9095

resilience4j:
  circuitbreaker:
    configs:
      default:
        slidingWindowSize: 100
        permittedNumberOfCallsInHalfOpenState: 10
        waitDurationInOpenState: 5s
        failureRateThreshold: 50
        eventConsumerBufferSize: 10
        registerHealthIndicator: true
        minimumNumberOfCalls: 5
        retryExceptions:
          - org.springframework.web.client.HttpServerErrorException
          - java.io.IOException
    instances:
      BlogService:
        baseConfig: default
