version: '3'

services:
  sks-postgres:
    image: postgres:14.1-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: pass
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    container_name: sks-postgres-14
    restart: on-failure
