eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

spring:
  cloud:
    gateway:
      routes:
        - id: author-service
          uri: lb://author-sevice
          predicates:
            - Path=/author-service/**
          filters:
            - StripPrefix=1
        - id: blog-service
          uri: lb://blog-sevice
          predicates:
            - Path=/blog-service/**
          filters:
            - StripPrefix=1
        - id: location-service
          uri: lb://location-sevice
          predicates:
            - Path=/location-service/**
          filters:
            - StripPrefix=1

  application:
    name: gateway

server:
  port: 9090
