spring:
  cloud:
    gateway:
      routes:
        - id: AUTHOR-SERVICE
          uri: lb://AUTHOR-SERVICE
          predicates:
            - Path=/authors/**
        - id: BLOG-SERVICE
          uri: lb://BLOG-SERVICE
          predicates:
            - Path=/blogs/**
        - id: LOCATION-SERVICE
          uri: lb://LOCATION-SERVICE
          predicates:
            - Path=/locations/**

  application:
    name: gateway

server:
  port: 9090
