spring:
  application:
    name: author-service

server:
    port: 9091

resilience4j:
  circuitbreaker:
    configs:
      default:
        slidingWindowSize: 100
        permittedNumberOfCallsInHalfOpenState: 10
        waitDurationInOpenState: 5s
        failureRateThreshold: 50
        eventConsumerBufferSize: 10
        registerHealthIndicator: true
        minimumNumberOfCalls: 5
        retryExceptions:
          - org.springframework.web.client.HttpServerErrorException
          - java.io.IOException
    instances:
      AuthorService:
        baseConfig: default
